### ISSUE TITLE
504 gateway timeouts

### ISSUE THREAD

**Issue by ukscone** [PiSupply/iot-lora-image#14]
After the first time i look at the dashboard I get a lot of 504 gateway timeout nginx..... errors. refresh will sometimes work but eventually it'll end up on a 504 page and that's it. the dashboard will not come up again

**Comment by ryanteck** [comment]
Still have not been able to replicate this however have implemented some precautionary changes.

@ukscone When the new SD Card is ready I'll ask you to test this out to see if this issue is fixed if that's OK. Target is next Sunday for release. 

To-Do:

- [ ] Change NGINX Timeout slightly

**Comment by ryanteck** [comment]
This requires the following modifications:
in php.ini ```max_execution_time=300```
in www.conf ```request_terminate_timeout = 300```
in nginx.conf ``` fastcgi_read_timeout 300;```

**Comment by ukscone** [comment]
ok will tryout the new sd image when it's ready

**Comment by ryanteck** [comment]
@ukscone The new SD Card image is up at https://github.com/PiSupply/iot-lora-image/releases/tag/2019-07-27
