### ISSUE TITLE
Move config files to admin folder and protect with .htpasswd

### ISSUE THREAD

**Issue by m0lmk** [PiSupply/iot-lora-image#3]
It would be great if the config files were moved to an admin folder and protected with a .htpasswd. I have done this on my dev system and it works well.

The status page remains public so that it can be viewed across the LAN but the config pages become protected so the settings can't be changed without authorisation.

**Comment by ryanteck** [comment]
Started to implement this and will be in a new image soon.

All files are password protected accept index.php, image, js, css and a new incorrect password page.

**Comment by ryanteck** [comment]
I believe this has been implemented in the last few releases now. Closing ticket.
