### ISSUE TITLE
server information not reloaded after reboot

### ISSUE THREAD

**Issue by rangerjo** [PiSupply/iot-lora-image#46]
Everything works fine. However, rebooting the controller does not load the server defined in `/opt/iotloragateway/local_conf.json` and does not push packages to ttn. Investigation shows the following:

```
pi@iotloragateway:/opt/iotloragateway $ sudo journalctl -fu iot-lora-gateway 
-- Logs begin at Thu 2019-02-14 10:11:58 GMT. --
Jan 28 19:49:59 iotloragateway iot-lora-gateway[652]: src/ttn_transport.c:371:ttn_connect(): ttn_connect: sleeping() at 230, total 240
Jan 28 19:49:59 iotloragateway iot-lora-gateway[652]: 19:49:59  ERROR: [TTN] Connection to server "" failed, retry in 480 seconds
```

Simply running `sudo systemctl restart iot-lora-gateway` loads the settings from `local_conf.json` and everything works as expected again. This looks like a bug to me!

**Comment by ryanteck** [comment]
Hi @rangerjo ,

I've re-written most of the software from scratch for the next release which includes many updates and improvements where this is resolved.

I'll close this ticket for now but will update it when the new version is released.

Thanks -
Ryan
