### ISSUE TITLE
Add Papirus support

### ISSUE THREAD

**Issue by ryanteck** [PiSupply/iot-lora-image#52]
See if it's possible, and if it is add support in for Papirus to be used for monitoring.

**Comment by ryanteck** [comment]
Uses slightly too many pins.

**Comment by shawaj** [comment]
Could possibly add media center hat for monitoring?

**Comment by ryanteck** [comment]
Same issue as why I had to close this early, too many pin conflicts
unfortunately.  Got another idea I'll pop over via email.
