### ISSUE TITLE
lora image with sim800 ppp doesnt work

### ISSUE THREAD

**Issue by krishnakulkarni88** [PiSupply/iot-lora-image#73]
Hi,
Thanks for the image it works really well. But when I integrated PPP with sim800 it's not working.
I thought it was my problem and checked with another sd card which has only rasbian image. In another sd card, it's working fine
can you help me solve this issue?

**Comment by ryanteck** [comment]
We've had issues ourselves with the sim 800. We're working on a new version of the LoRa software with 4G support but believe this is only going to primarily support the EC-25 so can't really help to a certain extent.

Part of this is debian to blame as the 4G module Support isn't as good as Ubuntus. But really to a certain extent I can't support many more than the 4G module we'll be using.

**Comment by ryanteck** [comment]
Actually, we might be able to support the SIM7100 which i'm hoping will be similar to the sim800's config. But it'll be a good couple of weeks yet as progress with 4G has been tricky so far.

**Comment by ryanteck** [comment]
@krishnakulkarni88 do you have a link of the module add-on you are using?

**Comment by krishnakulkarni88** [comment]
Thanks for the reply, I am attaching my gateway module which I am using.
https://www.digikey.com/catalog/en/partgroup/iot-lora-gateway-hat-for-raspberry-pi-board/90535

**Comment by ryanteck** [comment]
Sorry,  I meant what board for the LTE module.

**Comment by krishnakulkarni88** [comment]
actually we are using 2g board, sim800 
https://www.wish.com/product/sim800-gsm-gprs-module-shield-development-study-board-51-stm32-sim900a-5b4ba64e5df38d47cf0a4876?hide_login_modal=true

**Comment by ryanteck** [comment]
That one we won't be able to support I don't think as I assume you're using UART? We'll only be able to support a select set of USB ones.

**Comment by krishnakulkarni88** [comment]
ok, thank you for your time. 
If I try to install this gateway setup manually in another rasbian os how can I do that? because I have tried a few methods by cloning ic880a repo and installing the sh file but it is not working. but your image starts to work immediately. May I know the procedure on how to install it manually. and also I have changed the pin number in sh file to 17th pin and enable spi still it doesn't work.

**Comment by ryanteck** [comment]
It sounds like you're using the wrong pin as it's not GPIO 17 and is instead GPIO 22 / BCM 22 number.

**Comment by krishnakulkarni88** [comment]
hey, thanks your solution worked, but as you said above ec25 works in Lora image. I tried connecting USB cable of ec25 dev kit and installed PPP. it is showing ip in ifconfig but when I do ping google.com it is giving me name resolution error

**Comment by ryanteck** [comment]
Sorry, I meant that in the next version we'll support EC25 out of the box among lots of other improvements. We may also be supporting the SIM7100 too at the same time in the new version. But currently neither are supported in the current image.
